[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.150.1" # Use the latest version number from https://github.com/gohugoio/hugo/releases

[context.production.environment]
  HUGO_ENV = "production"